name: place_see_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0                 # HTTP-клиент для запросов
  flutter_secure_storage: ^9.0.0  # безопасное хранение токенов
  hive: ^2.2.3
  hive_flutter: ^1.1.0        # локальный кэш
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.3.1
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.0.0
  build_runner: ^2.4.6

flutter_gen:
  output: lib/gen
  integrations:
    flutter_svg: true

flutter:
  assets:
    - .env
    - assets/icons/
  uses-material-design: true
  fonts:
    - family: NT Somic
      fonts:
        - asset: assets/fonts/01_NTSomic-Regular.ttf
        - asset: assets/fonts/03_NTSomic-Bold.ttf
          weight: 900
        - asset: assets/fonts/02_NTSomic-Medium.ttf
          weight: 500