name: place_see_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0                 # HTTP-клиент для запросов
  flutter_secure_storage: ^10.0.0  # безопасное хранение токенов
  hive: ^2.2.3
  hive_flutter: ^1.1.0        # локальный кэш
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.3.1
  marquee: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  photo_view: ^0.15.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  image_picker: ^1.2.1
  http_parser: ^4.1.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage_web: ^2.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  intl: ^0.19.0

flutter_gen:
  output: lib/gen
  integrations:
    flutter_svg: true

flutter:
  assets:
    - .env
    - assets/icons/
  uses-material-design: true
  fonts:
    - family: NT Somic
      fonts:
        - asset: assets/fonts/01_NTSomic-Regular.ttf
        - asset: assets/fonts/03_NTSomic-Bold.ttf
          weight: 900
        - asset: assets/fonts/02_NTSomic-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/outer_icons/main_image.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/outer_icons/main_image.png"
  monochrome_icon: "assets/icons/outer_icons/main_image.png"
  remove_alpha_ios: true
